### ISSUE TITLE
Double-dash separator not added for signatures

### ISSUE THREAD

**Issue by wichert** [mimestream/new-bugs#16]
**Describe the bug**
Signatures in emails should be preceded by a line containing dash-dash-space (`-- `). Gmail does that automatically: when you compose with a signature it will automatically add that line. Mimestream needs to do that as well.

**To Reproduce**

1. Configure a Gmail signature for an account
2. Create a new email using that account
3. Notice the signature is shown, but no `-- ` line was added

**Expected behavior**
A `-- ` is added before the signature.

**Screenshots**

New email with signature as seen in Gmail:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/199657/95430422-06bac500-094c-11eb-8ed7-7ebecbf9e2e2.png">

New email with signature as seen in mimestream:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/199657/95430375-fdc9f380-094b-11eb-87c8-312d331ed6d0.png">

Please add screenshots to help explain your problem.

**Configuration:**
 - OS: macOS Catalina 10.15.7
 - Mimestream Version 0.6.26

**Comment by neiljhaveri** [comment]
Thanks for filing this feedback!

Unfortunately, the Gmail API doesn't have a way for Mimestream to sync this setting's value, so you have to disable it in Mimestream to get the "--" separator back. This is the default value in Mimestream because it's the new default in Gmail too. Please see the following screenshot:
<img width="636" alt="Screen Shot 2020-10-08 at 1 15 13 PM" src="https://user-images.githubusercontent.com/24994368/95491956-6030ed00-0968-11eb-9374-ce2fa68dd53d.png">
